spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: hospital-service
          uri: lb://hospital-service
          predicates:
            - Path=/hospitals/**
        - id: donor-service
          uri: lb://donor-service
          predicates:
            - Path=/donors/**
        - id: camp-service
          uri: lb://camp-service
          predicates:
            - Path=/camps/**
        - id: donation-service
          uri: http://localhost:8082
          predicates:
            - Path=/donations/**
        - id: blood-service
          uri: http://localhost:8083
          predicates:
            - Path=/bloods/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
