spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: donor-service
          uri: lb://donor-service
          predicates:
            - Path=/donor/**

        - id: donation-service
          uri: lb://donation-service
          predicates:
            - Path=/donation/**

        - id: blood-service
          uri: lb://blood-service
          predicates:
            - Path=/blood/**

        - id: camp-service
          uri: lb://camp-service
          predicates:
            - Path=/camp/**

        - id: hospital-service
          uri: lb://hospital-service
          predicates:
            - Path=/hospital/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
logging:
  level:
   org.springframework.security: DEBUG

